### ISSUE TITLE
[1.16.5] Pillagers no longer able to use their crossbows

### ISSUE THREAD

**Issue by NighthowlerStudios** [Lupicus/MobPC#1]
Mobs such as pillagers will continuously update their AI in timings that makes it impossible for them to fully charge their crossbow, making it impossible for them to use it.  This only occurs if your mod is installed at the time in my modpack, which contains Roadrunner.

**Comment by Lupicus** [comment]
Not sure how that is possible, I'm not changing any AI, just test item they pickup and optionally skipping making them persistent, which should only affect despawning code.

**Comment by NighthowlerStudios** [comment]
I'm not sure how either.  All I know is it happens.  Maybe the loading mechanism is firing a check for their inventory (which has the arrow you can swap for potion arrows with commands etc) which fires your mod?

**Comment by NighthowlerStudios** [comment]
it could be some other mod colliding as well but I'm just unsure.  they just stand there and keep trying to charge the crossbow, which never gets full

**Comment by Lupicus** [comment]
The code change is in the MobEntity and only called when picking items off the ground.

**Comment by NighthowlerStudios** [comment]
strange.  guess I will keep researching that bug some other time.  must have been a spoof removing yours fixed something

**Comment by Lupicus** [comment]
I can test it.

**Comment by NighthowlerStudios** [comment]
pack's recent update is available on curseforge here:

install your mod manually

https://www.curseforge.com/minecraft/modpacks/kaleidios-battle-pack/files/3629701

**Comment by Lupicus** [comment]
I initially loaded my mod and roadrunner and teleport to pillager outpost and switched to survival and they started shooting me.
I'll load your pack with my mod and see.

**Comment by NighthowlerStudios** [comment]
try seeing if giving them some other enemy to focus on helps, such as getting them to hit some other mob, or chase a villager

**Comment by Lupicus** [comment]
still with just those 2 mods, summoned a villager and the pillager shot it several times and then killed the villager.

**Comment by Lupicus** [comment]
going to give the modpack a try, my machine isn't super, so I might have to get my friend to test it, if things are too slow.

**Comment by NighthowlerStudios** [comment]
the pack runs at 60 fps on a mac pro if you have optifine installed so...shouldn't be too awful.  without optifine it gets 300 fps on my machine which is 75% vanilla.  I went through hell to optimize the pack

**Comment by Lupicus** [comment]
oh, I'm just running single player game, does the bug happen there too or just with dedicated server?

**Comment by NighthowlerStudios** [comment]
seemingly dedicated server

**Comment by Lupicus** [comment]
I saw one fire at a villager (with open hand), most of them are carrying items in one of their hands, like a bucket of lava and flint and steel, not sure they can fire crossbow with something in their hands, I'd have to check though. That doesn't seem to be the case...one with lava bucket will shoot.

**Comment by NighthowlerStudios** [comment]
strange.  I have no clue what caused the issue on my end then.  I will investigate more some other time.  until then I believe it might not be this mod at fault.

**Comment by Lupicus** [comment]
Well, I tested the 2 mods only and the pillager was actively going after villager. The modpack without ModPC, the pillager did shoot, but was standing around a lot and not actively moving toward the villager. Sure seems like something else is modifying the AI in a bad way.

**Comment by Lupicus** [comment]
FYI, if I only load bigbrain and recruits mods, the crossbow pillager hardly fires and sometimes turns his back to the villager.

**Comment by NighthowlerStudios** [comment]
okay, I have a feeling bigbrain is at fault here.  thank you
